### PR TITLE
Improved UI and searching

### LINKED ISSUE #22: Text searching
In `publications.php` it would great to be able to search for:

* PMID
* Author name (related to #20 )
* Keywords (related to #20) 
* Title (maybe)
* DOI (maybe)

### PR DESCRIPTION
**Pull request by alneberg**
- Made it possible to "search" publications (related to #22) using:
   - Pubmed id
   - Search for title
   - Author email

 - Made it possible to link to publications using pubmed id
 - Renamed "Researchers and Labs"-tab to only "Labs"
 - Made it possible to find labs by name
 - Created a new tab called "Researchers" where researchers are listed.
 - Made it possible to search for individual researchers and look up their respective papers
 - Made the author name clickable on the publications view (related to #20)

Just drop by my desk for a live preview.

**Edit:**
 - Added links from keywords to all publications with that keyword
 - Made it possible to search for DOI and Keywords (one at a time). Closes #22

### CODE REVIEW

**Comment by alneberg** [comment]
Ah, yeah the searching is definitely not fool proof. It will probably never be completely sql injection safe but I could have a look at not messing up things with common search strings at least.

**Comment by ewels** [comment]
Uhhhh, it should _definitely_ be injection safe. PHP has a tonne of built in functionality for this - see `mysqli_real_escape_string` ([docs](http://php.net/manual/en/mysqli.real-escape-string.php)).

PHP `trim()` to get rid of whitespace.

Phil

**Comment by alneberg** [comment]
Ah, yes that wasn't so difficult. This should hopefully work better against hackers and regular MC hammer users @remiolsen.

**Comment by alneberg** [comment]
Ok @remiolsen, should be ready to be tested again now!

**Comment by ewels** [comment]
Sorry for my strong reaction! The words _sql injection_ send shivers down my spine and bring me out in a cold sweat to this day. Blame my background as a (shitty teenage) web dev.. 😆

**Comment by remiolsen** [comment]
Nice @alneberg! I'm happy with this.

**Pull request merged**
